name: Prueba num 1

on:
  push:
    branches:
      - master

jobs:
  decir-hola:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Hola mundo"
      - name: Enviar solicitud POST
        run: >
          curl -X POST 'https://webhook.site/892f2749-aba3-44c8-af63-04640edf7a85' -H "Content-Type: application/json" -d '{"Nombre":"Harol"}'



  