name: Prueba num 1

on:
  push:
    branches:
      - master

jobs:
  decir-hola:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Hola mundo"
      - name: Enviar Peticion
        run: |
  curl -X POST "https://webhook.site/" -H "Content-Type: application/json" -d '{"Nombre":"MessiGoat"}'

  